// Public compiled CLI/MCP proof on a fresh private Mini. No primary mutation.
import assert from "node:assert/strict";
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,openSync,closeSync,existsSync,realpathSync} from "node:fs";
import {join,resolve} from "node:path";
import {parseArgs} from "node:util";
import {homedir} from "node:os";
import {Client} from "@modelcontextprotocol/sdk/client/index.js";
import {StdioClientTransport} from "@modelcontextprotocol/sdk/client/stdio.js";
import {readConfig} from "../src/config.ts";
import {CARD_FIELDS,allPinnedSchemas,DEFAULT_COLUMNS} from "../src/schemas.ts";
import {boardCardFieldsFromCard,boardCardSk} from "../src/board-cards.ts";
import {sha256,COMPOUND_CARD_BUILD,COMPOUND_CARD_BUILDS} from "../src/guarded-snapshot.ts";

const {values}=parseArgs({args:process.argv.slice(2),strict:true,allowPositionals:false,options:{"artifact-root":{type:"string"},"mini-bin":{type:"string"},"mini-build":{type:"string"},"dedupe-mode":{type:"string",default:"off"},help:{type:"boolean"}}});
if(values.help){console.log("Usage: bun scripts/probe-guarded-card-public.ts [--artifact-root PATH] [--mini-bin PATH] [--mini-build BUILD] [--dedupe-mode off|on]");process.exit(0);}
const source=new URL("../",import.meta.url).pathname,binary=resolve(values["mini-bin"]??join(homedir(),".lastdb/current/lastdbd"));
const miniBuild=values["mini-build"]??COMPOUND_CARD_BUILD;assert(COMPOUND_CARD_BUILDS.includes(miniBuild));assert(["off","on"].includes(values["dedupe-mode"]!));
const version=Bun.spawnSync([binary,"--version"],{stdout:"pipe",stderr:"pipe"});assert.equal(version.exitCode,0);assert.equal(new TextDecoder().decode(version.stdout).trim(),"lastdbd "+miniBuild);
const artifactRoot=realpathSync(resolve(values["artifact-root"]??join(source,"dist")))+"/";
const root=mkdtempSync("/tmp/fkanban-public-guard-"),home=join(root,"home"),proxyDir=join(root,"proxy");
mkdirSync(join(home,"data"),{recursive:true});mkdirSync(proxyDir);
const socket=join(home,"data","folddb.sock"),full=join(home,"data","folddb-full.sock"),proxy=join(proxyDir,"folddb.sock"),proxyFull=join(proxyDir,"folddb-full.sock");
const cfgPath=join(root,"config.json"),evidencePath=join(root,"evidence.json"),startTime=Date.now();
assert(realpathSync(root).startsWith(realpathSync("/tmp")+"/fkanban-public-guard-"));
const artifact=JSON.parse(readFileSync(artifactRoot+"guarded-contract.json","utf8"));
const sourceSha=()=>sha256(JSON.stringify(artifact.source_manifest.map((f:any)=>({path:f.path,sha256:sha256(readFileSync(source+f.path))}))));
assert.equal(sourceSha(),artifact.source_manifest_sha256);assert.equal(sha256(readFileSync(artifactRoot+"kanban")),artifact.cli_sha256);assert.equal(sha256(readFileSync(artifactRoot+"kanban-mcp")),artifact.mcp_sha256);
const before=sourceSha(),pins=readConfig().schemaHashes;
const schemaHashes={card:pins.card!,board:pins.board!,board_cards:pins.board_cards!};
assert(Object.values(schemaHashes).every(h=>/^[0-9a-f]{64}$/.test(h)));
const evidence:any={version:1,root,artifact_root:artifactRoot,build:miniBuild,mini_binary:binary,mini_binary_sha256:sha256(readFileSync(binary)),dedupe_mode:values["dedupe-mode"],started_at:new Date().toISOString(),program_sha256:sha256(readFileSync(import.meta.path)),artifact,requests:0,public_batches:[],cases:[],result:"pending",source_unchanged:false};
const expected=new Map<string,any>(),destinations=new Map<string,any>(),absentDestinations=new Set<string>(),readbackPending=new Set<string>();let eventSeq=0;
let userHash="",child:ReturnType<typeof Bun.spawn>|undefined,mcp:Client|undefined;
const pause=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function budget(){assert(++evidence.requests<=1500,"request cap");assert(Date.now()-startTime<600000,"wall cap");}
async function raw(path:string,body?:unknown){budget();const r=await fetch("http://localhost"+path,{unix:full,method:body===undefined?"GET":"POST",headers:{"Content-Type":"application/json","X-LastDB-Client":"fkanban-public-guard-proof",...(userHash?{"X-User-Hash":userHash}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(90000)} as any);const text=await r.text();return {status:r.status,json:JSON.parse(text)};}
function op(schema:string,hash:string,range:string|null,fields:any,type="update"){return {type:"mutation",schema,fields_and_values:fields,key_value:{hash,range},mutation_type:type,durability:"durable"};}
async function batch(ops:any[]){assert(ops.length<=256);const r=await raw("/api/mutations/batch",ops);assert.equal(r.status,200,JSON.stringify(r.json));assert.equal(r.json.durability,"durable");return r.json;}
async function readKeys(schema:string,keys:[string,string][],fields:string[]){const r=await raw("/api/query",{schema_name:schema,filter:{HashRangeKeys:keys},fields,limit:1000,offset:0});assert.equal(r.status,200,JSON.stringify(r.json));assert.equal(r.json.ok,true);assert.equal(r.json.has_more,false);assert.equal(r.json.unresolved_rows??0,0);return r.json;}
async function current(slug:string){return (await readKeys(schemaHashes.card,[[slug,""]],[...CARD_FIELDS])).results[0]?.fields??null;}
function save(){evidence.source_unchanged=sourceSha()===before;writeFileSync(evidencePath,JSON.stringify(evidence,null,2)+"\n");}
async function start(){assert(!child);const fd=openSync(join(root,"boot.log"),"a",0o600);child=Bun.spawn([binary,"--data-dir",home,"--socket-path",socket,"--full-socket-path",full],{env:{PATH:process.env.PATH??"/usr/bin:/bin",LASTDB_HOME:home,FOLDDB_HOME:home,TMPDIR:root,RUST_LOG:"warn",LASTDB_WRITE_DEDUPE:values["dedupe-mode"]==="on"?"1":"0"},stdout:fd,stderr:fd});closeSync(fd);evidence.pids??=[];evidence.pids.push(child.pid);for(let n=0;n<45;n++){if(child.exitCode!==null)throw Error("private Mini exited");if(existsSync(full)){try{const r=await raw("/api/version");if(r.status===200){assert.equal(r.json.build,miniBuild);evidence.instances??=[];evidence.instances.push(r.json.instance_id);return;}}catch(e){if(String(e).includes("AssertionError"))throw e;}}await pause(1000);}throw Error("private Mini readiness timeout");}
async function stop(signal:"SIGKILL"|"SIGTERM"){if(!child)return;if(child.exitCode!==null){child=undefined;return;}const p=child.pid;const ps=Bun.spawnSync(["/bin/ps","-o","command=","-p",String(p)],{stdout:"pipe",stderr:"pipe"});const argv=new TextDecoder().decode(ps.stdout);assert(argv.includes(binary)&&argv.includes("--data-dir "+home)&&argv.includes("--socket-path "+socket));assert(!argv.includes(join(homedir(),".lastdb/data")));child.kill(signal);await Promise.race([child.exited,pause(10000).then(()=>{throw Error("private Mini stop timeout");})]);child=undefined;evidence.stop_checks??=[];evidence.stop_checks.push({pid:p,signal,argv_verified:true});}
type Arm={slug:string,stage:number,field?:string,value?:any,ack?:string,failClear?:boolean,readback?:boolean};
let arm:Arm|undefined,stage=0,lastRead=new Map<string,number>(),readCompleteSeq=new Map<string,number>();
const forward=async(req:Request)=>{
  budget();const path=new URL(req.url).pathname,body=req.method==="GET"?undefined:await req.text();let parsed:any;try{parsed=body?JSON.parse(body):undefined;}catch{}
  const canonicalRead=path==="/api/query"&&parsed?.schema_name===schemaHashes.card&&parsed.fields?.length===23&&Array.isArray(parsed?.filter?.HashRangeKeys);
  const rows=path==="/api/mutations/batch"&&Array.isArray(parsed)?parsed:[];
  const final=rows.find((r:any)=>r.schema===schemaHashes.card&&Object.keys(r.fields_and_values??{}).length===23);
  let active:Arm|undefined;
  if(final){assert(rows.length>=25&&rows.length<=26,"public batch op cap");assert.equal(rows.filter((r:any)=>r.expected?.type==="value").length,23);assert(rows.every((r:any)=>r.durability==="durable"));evidence.public_batches.push({slug:final.key_value.hash,ops:rows.length,guards:rows.filter((r:any)=>r.expected).map((r:any)=>r.expected.field),last_canonical_read:lastRead.get(final.key_value.hash),destination_key:rows.find((r:any)=>r.schema===schemaHashes.board_cards)?.key_value.range});if(arm?.slug===final.key_value.hash&&++stage===arm.stage){active=arm;assert(lastRead.has(arm.slug),"barrier has no canonical read");if(active.field){const lastCanonicalResponseSeq=readCompleteSeq.get(active.slug);assert(lastCanonicalResponseSeq);const beforeRaw=await current(active.slug);const guarded=Object.fromEntries(rows.filter((r:any)=>r.expected).map((r:any)=>[r.expected.field,r.expected.value]));assert.deepEqual(beforeRaw,guarded,"pre-barrier differs from retained atomic witness");assert.notDeepEqual(beforeRaw[active.field],active.value,"barrier mutated no field");await batch([op(schemaHashes.card,active.slug,null,{[active.field]:active.value})]);const humanDurableAckSeq=++eventSeq;const afterRaw=await current(active.slug),changed=CARD_FIELDS.filter(f=>JSON.stringify(beforeRaw[f])!==JSON.stringify(afterRaw[f]));assert.deepEqual(changed,[active.field]);assert.deepEqual(afterRaw,{...beforeRaw,[active.field]:active.value});expected.set(active.slug,afterRaw);evidence.cases.push({name:`barrier-${active.slug}`,field:active.field,changed_fields:changed,all_other_fields_unchanged:changed.length===1,last_canonical_response_seq:lastCanonicalResponseSeq,human_durable_ack_seq:humanDurableAckSeq,after_final_read:humanDurableAckSeq>lastCanonicalResponseSeq!,prior_value:beforeRaw[active.field],human_value:active.value});}if(active.failClear){arm=undefined;return Response.json({error:"service_timeout",message:"private proof clear barrier"},{status:503});}}}
  const batchForwardSeq=rows.length?++eventSeq:undefined;if(active?.field){const event=evidence.cases.at(-1);event.batch_forward_seq=batchForwardSeq;event.before_batch_forward=event.human_durable_ack_seq<batchForwardSeq!;assert(event.after_final_read&&event.before_batch_forward);}
  const r=await fetch("http://localhost"+path,{unix:full,method:req.method,headers:req.headers,body,signal:AbortSignal.timeout(30000)} as any);const text=await r.text();
  if(canonicalRead && r.status===200)for(const [slug]of parsed.filter.HashRangeKeys){lastRead.set(slug,Date.now());readCompleteSeq.set(slug,++eventSeq);if(readbackPending.delete(slug)){const changed=JSON.parse(text);changed.results[0].fields.body="private readback mismatch";evidence.cases.push({name:"stage1-readback-barrier",slug,after_durable_ack:true});return Response.json(changed);}}
  if(final&&r.status===200){const state=structuredClone(final.fields_and_values);expected.set(final.key_value.hash,state);for(const row of rows.filter((r:any)=>r.schema===schemaHashes.board_cards))destinations.set(row.key_value.range,{...row.fields_and_values});}
  if(active?.readback && final && r.status===200)readbackPending.add(final.key_value.hash);
  if(active?.ack){arm=undefined;return active.ack==="malformed"?new Response("not JSON",{status:200}):Response.json(active.ack==="missing"?{}:{durability:active.ack});}
  if(active)arm=undefined;
  return new Response(text,{status:r.status,headers:{"Content-Type":r.headers.get("Content-Type")??"application/json"}});
};
let proxyServer:ReturnType<typeof Bun.serve>|undefined,fullServer:ReturnType<typeof Bun.serve>|undefined;
const baseEnv=()=>({PATH:process.env.PATH??"/usr/bin:/bin",HOME:join(root,"user"),LASTDB_HOME:home,FOLDDB_HOME:home,FOLDDB_SOCKET_PATH:proxy,KANBAN_CONFIG:cfgPath,FKANBAN_CONFIG:cfgPath,TMPDIR:root,FKANBAN_FSITUATIONS_BIN:join(root,"situations")});
async function cli(args:string[],witness?:string){const flags:string[]=[];if(witness!==undefined){const p=join(root,"witness.json");writeFileSync(p,witness);flags.push("--guard-snapshot",p,"--snapshot-sha256",sha256(witness));}const p=Bun.spawn([artifactRoot+"kanban",...args,...flags,"--json"],{env:baseEnv(),stdout:"pipe",stderr:"pipe"});const [stdout,stderr,exit]=await Promise.all([new Response(p.stdout).text(),new Response(p.stderr).text(),p.exited]);let json:any;try{json=JSON.parse(stdout);}catch{}writeFileSync(join(root,"last-cli.stdout"),stdout);writeFileSync(join(root,"last-cli.stderr"),stderr);return {exit,stdout,stderr,json};}
async function snapshot(slug:string){const r=await cli(["guarded-snapshot",slug]);assert.equal(r.exit,0,r.stderr);assert.equal(r.stdout.endsWith("\n"),true);assert.equal(JSON.parse(r.stdout).fields.slug,slug);return r.stdout;}
async function tool(name:string,args:any,witness?:string){const r=await mcp!.callTool({name,arguments:{...args,...(witness===undefined?{}:{guard_snapshot_json:witness,snapshot_sha256:sha256(witness)})}});const json=r.structuredContent??JSON.parse((r.content as any)[0].text);return {isError:r.isError===true,json,content:r.content};}
function receipt(result:any){assert.equal(result.durability,"durable");assert.equal(typeof result.next_snapshot_json,"string");assert.equal(sha256(result.next_snapshot_json),result.next_snapshot_sha256);assert(result.next_snapshot_json.endsWith("\n"));return result.next_snapshot_json as string;}
const ids={chain:"public-chain",raw:CARD_FIELDS.map(f=>"race-"+f),claim:["claim-initial-body","claim-initial-hold","claim-clear-body","claim-clear-hold","claim-mcp-clear"],ack:["ack-memory","ack-missing","ack-malformed"],mcp:"public-mcp",goal:"sequential-goal",resume:"resume-valid",overlap:"resume-overlap",claimAck:"claim-ack-memory",claimReadback:"claim-readback"};
function card(slug:string,column="doing",owner="worker",rawEmpty=false){return Object.fromEntries(CARD_FIELDS.map(f=>[f,f==="tags"?["p1","raw","raw"]:f==="deps"?[]:f==="surfaces"?[`src/${slug}.ts`]:({slug,title:"Private public contract fixture",body:`## GOAL\nTest the finite public Card command.\n## END STATE\nPROOF: PASS private fixture\nRepo: EdgeVector/fkanban\nBase: main\nKind: pr`,board:"default",column,position:"100",assignee:owner,created_at:"2026-10-08T00:00:00Z",updated_at:"2026-10-08T00:00:00Z",created_by:"",repo:"EdgeVector/fkanban",base:"main",kind:"pr",block_status:rawEmpty?"":"none"} as any)[f]??""]));}
try{
 console.log(JSON.stringify({stage:"start",root}));await start();let identity=await raw("/api/system/auto-identity");if(identity.status===503)identity=await raw("/api/setup/bootstrap",{name:"fkanban-private-public-proof"});assert.equal(identity.status,200);userHash=identity.json.user_hash;assert.equal(typeof userHash,"string");
 const loaded=await raw("/api/schemas/load",{schemas:Object.values(schemaHashes)});assert.equal(loaded.status,200,JSON.stringify(loaded.json));assert.deepEqual(loaded.json.failed_schemas??[],[]);
 const metadata=await Promise.all(Object.values(schemaHashes).map(h=>raw("/api/schema/"+h)));assert(metadata.every(r=>r.status===200));
 writeFileSync(cfgPath,JSON.stringify({configVersion:1,nodeUrl:"http://localhost",nodeSocketPath:proxy,schemaServiceUrl:"http://unused.invalid",userHash,schemaHashes,enforceLivePrMilestone:false}));
 const bun=Bun.spawnSync(["which","bun"],{stdout:"pipe"});writeFileSync(join(root,"situations"),`#!${new TextDecoder().decode(bun.stdout).trim()}\nconsole.log(JSON.stringify({ok:true}));\n`,{mode:0o700});
 const cards=[card(ids.chain,"backlog","",true),...ids.raw.map(s=>card(s)),...ids.claim.map(s=>card(s,"todo","")),...ids.ack.map(s=>card(s)),card(ids.mcp),card(ids.goal),card(ids.resume,"todo",""),card(ids.overlap,"todo",""),card(ids.claimAck,"todo",""),card(ids.claimReadback,"todo","")];
 const boardFields={slug:"default",title:"Private proof",body:"",columns:[...DEFAULT_COLUMNS],created_at:"test",updated_at:"test"};
 await batch([op(schemaHashes.board,"default",null,boardFields),...cards.map(c=>op(schemaHashes.card,c.slug,null,c))]);for(const c of cards)expected.set(c.slug,c);
 proxyServer=Bun.serve({unix:proxy,fetch:forward});fullServer=Bun.serve({unix:proxyFull,fetch:forward});
 const native=await readKeys(schemaHashes.card,[[ids.chain,""],["explicit-missing",""]],[...CARD_FIELDS]);evidence.native_response_shape={keys:Object.keys(native),returned_count:native.returned_count,total_count:native.total_count,has_more:native.has_more,next_cursor:native.next_cursor,unresolved_rows:native.unresolved_rows,row_keys:native.results.map((r:any)=>r.key)};
 const slugsPath=join(root,"slugs.json");writeFileSync(slugsPath,JSON.stringify([...cards.map(c=>c.slug),"explicit-missing"]));const br=await cli(["guarded-snapshot","--slugs-file",slugsPath]);assert.equal(br.exit,0,br.stderr);assert.deepEqual(br.json.items.map((i:any)=>i.slug),[...cards.map(c=>c.slug),"explicit-missing"]);assert.equal(br.json.items.at(-1).missing,true);const witnesses=new Map<string,string>(br.json.items.filter((i:any)=>!i.missing).map((i:any)=>{assert.equal(sha256(i.snapshot_json),i.snapshot_sha256);return [i.slug,i.snapshot_json];}));evidence.initial_witness_batch={keys:cards.length,requests:1};evidence.cases.push({name:"compiled-cli-native-batch",passed:true});
 const transport=new StdioClientTransport({command:artifactRoot+"kanban-mcp",env:baseEnv(),stderr:"pipe"});mcp=new Client({name:"private-public-proof",version:"1"},{capabilities:{}});await mcp.connect(transport);
 const mb=await tool("fkanban_guarded_snapshots",{slugs:[ids.mcp,"explicit-missing",ids.chain]});assert(!mb.isError);assert.equal(mb.json.items[1].missing,true);evidence.cases.push({name:"compiled-mcp-native-batch",passed:true});
 let w=witnesses.get(ids.chain)!;let r=await cli(["set",ids.chain,"--surfaces","src/checked.ts","--expect-assignee",""],w);assert.equal(r.exit,0,r.stderr);w=receipt(r.json);
 r=await cli(["move",ids.chain,"todo","--from","backlog","--expect-assignee",""],w);assert.equal(r.exit,0,r.stderr);w=receipt(r.json);
 r=await cli(["pickup","claim","--claim-v2","--only-card",ids.chain,"--worker","worker"],w);assert.equal(r.exit,0,r.stderr);assert.equal(r.json.result,"claimed");w=receipt(r.json);
 r=await cli(["mark",ids.chain,"PROOF: PASS compiled public chain","--expect-assignee","worker"],w);assert.equal(r.exit,0,r.stderr);w=receipt(r.json);
 r=await cli(["set",ids.chain,"--pr-url","https://github.com/EdgeVector/fkanban/pull/999999","--branch","private/proof","--expect-assignee","worker"],w);assert.equal(r.exit,0,r.stderr);w=receipt(r.json);
 r=await cli(["move",ids.chain,"done","--from","doing","--expect-assignee","worker"],w);assert.equal(r.exit,0,r.stderr);w=receipt(r.json);
 r=await cli(["mark",ids.chain,"HANDOFF: terminal retry","--expect-assignee","worker"],w);assert.equal(r.exit,0,r.stderr);w=receipt(r.json);assert.deepEqual(await current(ids.chain),JSON.parse(w).fields);evidence.cases.push({name:"compiled-cli-full-next-snapshot-chain-empty-status",passed:true});
 for(const [i,field]of CARD_FIELDS.entries()){const slug=ids.raw[i]!,w=witnesses.get(slug)!,old=expected.get(slug)[field],value=Array.isArray(old)?[...old,"human"]:`${old}-human`;arm={slug,stage:1,field,value};stage=0;const n=evidence.public_batches.length;const r=await cli(["mark",slug,"PROOF: PASS reject human race","--expect-assignee","worker"],w);assert.notEqual(r.exit,0,`${field} accepted`);assert.equal(arm,undefined,`${field} barrier absent`);assert.equal(evidence.public_batches.length,n+1,"unexpected fallback batch");const dest=boardCardSk("doing","100",slug);absentDestinations.add(dest);evidence.cases.push({name:`compiled-cli-post-read-${field}`,passed:true,canonical_unchanged:true,destination_absent:true});}
 for(const [i,slug]of ids.claim.entries()){const w=witnesses.get(slug)!,stageNum=i<2?1:2,field=i%2===0?"body":"block_status",value=field==="body"?expected.get(slug).body+"\nHUMAN GOAL: keep":stageNum===2?"deferred":"needs_human";arm={slug,stage:stageNum,field,value};stage=0;const n=evidence.public_batches.length;const r=i===4?await tool("fkanban_pickup_claim_v2",{card_slug:slug,worker:"worker"},w):await cli(["pickup","claim-v2","--only-card",slug,"--worker","worker"],w);const j=r.json;assert.equal(j.result,"error",JSON.stringify(r));assert.equal(evidence.public_batches.length,n+stageNum);if(stageNum===1){const finalBatch=evidence.public_batches.at(-1);absentDestinations.add(finalBatch.destination_key);}if(stageNum===2){assert.equal(j.code,"claim_recovery_pending");assert.equal(j.accepted_held.stage,"accepted-held");assert.equal(sha256(j.accepted_held.snapshot_json),j.accepted_held.snapshot_sha256);assert.equal(j.next_snapshot_json,undefined);assert((r as any).content===undefined||(r as any).content[0].text.includes("claim_recovery_pending"));}else assert.equal(j.accepted_held,undefined);evidence.cases.push({name:`compiled-${i===4?"mcp":"cli"}-claim-stage${stageNum}-${field}`,passed:true,result:j.result,code:j.code,accepted_held:stageNum===2});}
 for(const [i,slug]of ids.ack.entries()){const w=witnesses.get(slug)!;arm={slug,stage:1,ack:["memory","missing","malformed"][i]};stage=0;const n=evidence.public_batches.length;const r=await cli(["mark",slug,"PROOF: PASS ack uncertainty","--expect-assignee","worker"],w);assert.notEqual(r.exit,0);assert.equal(r.json?.next_snapshot_json,undefined);assert.equal(evidence.public_batches.length,n+1);evidence.cases.push({name:`compiled-public-${arm?.ack??ids.ack[i]}`,passed:true,no_receipt:true,no_retry:true});}
 let mw=witnesses.get(ids.mcp)!;let mr=await tool("fkanban_mark",{slug:ids.mcp,line:"PROOF: PASS compiled MCP",expect_assignee:"worker"},mw);assert(!mr.isError);mw=receipt(mr.json);mr=await tool("fkanban_set",{slug:ids.mcp,pr_url:"https://github.com/EdgeVector/fkanban/pull/999998",branch:"private/mcp",expect_assignee:"worker"},mw);assert(!mr.isError);mw=receipt(mr.json);mr=await tool("fkanban_move",{slug:ids.mcp,column:"done",from:"doing",expect_assignee:"worker"},mw);assert(!mr.isError);mw=receipt(mr.json);assert.deepEqual(await current(ids.mcp),JSON.parse(mw).fields);evidence.cases.push({name:"compiled-mcp-next-snapshot-chain",passed:true});
 const gw=witnesses.get(ids.goal)!,newBody=expected.get(ids.goal).body+"\nHUMAN GOAL: new scope";await batch([op(schemaHashes.card,ids.goal,null,{body:newBody})]);expected.set(ids.goal,{...expected.get(ids.goal),body:newBody});const gn=evidence.public_batches.length;const gr=await cli(["mark",ids.goal,"PROOF: PASS old scope","--expect-assignee","worker"],gw);assert.notEqual(gr.exit,0);assert.equal(evidence.public_batches.length,gn);evidence.cases.push({name:"sequential-same-owner-goal-old-witness",passed:true,zero_batches:true});
 const rw=witnesses.get(ids.resume)!;arm={slug:ids.resume,stage:2,failClear:true};stage=0;const rr=await cli(["pickup","claim-v2","--only-card",ids.resume,"--worker","worker"],rw);assert.equal(rr.json.result,"error");const held=rr.json.accepted_held;assert.equal(held.stage,"accepted-held");const without=await cli(["pickup","claim-v2","--only-card",ids.resume,"--worker","worker"]);assert.notEqual(without.json.result,"claimed");const resumed=await cli(["pickup","claim-v2","--only-card",ids.resume,"--worker","worker"],held.snapshot_json);assert.equal(resumed.json.result,"claimed",JSON.stringify(resumed));receipt(resumed.json);evidence.cases.push({name:"compiled-cli-accepted-held-error-then-exact-resume",passed:true});

 for(const [slug,mode]of [[ids.claimAck,"ack"],[ids.claimReadback,"readback"]]){arm={slug,stage:1,...(mode==="ack"?{ack:"memory"}:{readback:true})};stage=0;const n=evidence.public_batches.length;const bad=await cli(["pickup","claim-v2","--only-card",slug,"--worker","worker"],witnesses.get(slug)!);assert.equal(bad.json.result,"error");assert.equal(bad.json.accepted_held,undefined);assert.equal(bad.json.next_snapshot_json,undefined);assert.equal(evidence.public_batches.length,n+1);assert.equal(expected.get(slug).block_status,"needs_human");evidence.cases.push({name:`compiled-cli-initial-${mode}-unknown-no-recovery-receipt`,passed:true,code:bad.json.code});}
 arm={slug:ids.overlap,stage:2,failClear:true};stage=0;const hr=await cli(["pickup","claim-v2","--only-card",ids.overlap,"--worker","worker"],witnesses.get(ids.overlap)!);assert.equal(hr.json.result,"error");const hw=hr.json.accepted_held.snapshot_json,peer=card("later-human-overlap","doing","human");peer.surfaces=expected.get(ids.overlap).surfaces;peer.position="200";const peerProjection=boardCardFieldsFromCard(peer as any);await batch([op(schemaHashes.card,peer.slug,null,peer),op(schemaHashes.board_cards,"default",peerProjection.sk,peerProjection)]);expected.set(peer.slug,peer);destinations.set(peerProjection.sk,peerProjection);const hn=evidence.public_batches.length;const blocked=await cli(["pickup","claim-v2","--only-card",ids.overlap,"--worker","worker"],hw);assert.equal(blocked.json.result,"error");assert.equal(blocked.json.code,"guarded_peer_overlap");assert.equal(evidence.public_batches.length,hn);assert.equal(expected.get(ids.overlap).block_status,"needs_human");evidence.cases.push({name:"compiled-cli-held-resume-later-canonical-overlap",passed:true,zero_clear_batches:true});
 save();await mcp.close();mcp=undefined;await stop("SIGKILL");await start();
 const final=await readKeys(schemaHashes.card,[...expected.keys()].map(s=>[s,""]),[...CARD_FIELDS]);const byKey=new Map(final.results.map((r:any)=>[r.key.hash,r.fields]));for(const [s,c]of expected)assert.deepEqual(byKey.get(s),c,"restart canonical "+s);
 const bs=allPinnedSchemas().find(s=>s.key==="board_cards")!.schema.schema.fields,projection=await readKeys(schemaHashes.board_cards,[...new Set([...destinations.keys(),...absentDestinations])].map(sk=>["default",sk]),bs),byRange=new Map(projection.results.map((r:any)=>[r.key.range,r.fields]));for(const [sk,c]of destinations)assert.deepEqual(byRange.get(sk),c,"restart destination "+sk);for(const sk of absentDestinations)assert.equal(byRange.has(sk),false,"rejected destination exists "+sk);
 evidence.restart={passed:true,cards:expected.size,destinations:destinations.size,absent_destinations:absentDestinations.size};evidence.result="passed";
}catch(error){evidence.result="failed";evidence.error=error instanceof Error?`${error.name}: ${error.message}\n${error.stack??""}`:String(error);console.error(evidence.error);process.exitCode=1;}
finally{try{await mcp?.close();await stop("SIGTERM");}catch(e){evidence.stop_error=String(e);process.exitCode=1;}proxyServer?.stop(true);fullServer?.stop(true);save();assert(evidence.source_unchanged);console.log(JSON.stringify({result:evidence.result,root,evidencePath,cases:evidence.cases.length,requests:evidence.requests,restart:evidence.restart??null}));}
